name: Tests

on:
  push:
    paths:
      - '**.php'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - '.github/workflows/tests.yml'

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.4, 8.5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gd

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress
          composer dump

      - name: Run test phpunit
        run: composer test
